import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { PacificoNavbar } from '@/components/PacificoNavbar'
import ThemeRegistry from '@/components/Providers/ThemeRegistry'
import { PropsWithChildren } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeRegistry options={{ key: 'mui' }}>
        <PacificoNavbar items={[{label: 'Hola'}]}/>
        {children}
      </ThemeRegistry>
      </body>
    </html>
  )
}
